- name: tomcat-restart
  service: >
    name={{ service_tomcat }}
    state=restarted

- name: tomcat-start
  service: >
    name={{ service_tomcat }}
    state=started

- name: tomcat-stop
  service: >
    name={{ service_tomcat }}
    state=stopped
